#' @title Acquisition of Microbial Species
#' @description
#' This function determines the initial count of microbial species colonizing an individual, accounting for both the environmental and maternal communities of microorganisms. When saved as \var{acquiredSp}, it can be accessed by other functions.
#'
#' @usage
#' acquiredSpecies(pop,
#'                 parentPop = NULL,
#'                 founderM = NULL,
#'                 sym = NULL,
#'                 rndSeed = NULL,
#'                 globalSP = NULL)
#'
#' @param pop An object of class \code{\link{Pop-class}} generated with \pkg{\link{AlphaSimR}} representing the current population.
#' @param parentPop An object of class \code{\link{Pop-class}} generated with \pkg{\link{AlphaSimR}} representing the parental population. If \code{NULL}, the function assumes it needs to compute the microbiota for the base population.
#' @param founderM A list containing the details of the microbiota in the founder population, generated by \code{\link{setFounderM}}.
#' @param sym A value of 1 to consider the symbiosis effect on microbiota. This value is required when the population is not the base population.
#' @param rndSeed A seed value to initialize random sampling.
#' @param globalSP An object of class \code{\link{GlobalSP}} containing the global parameters of the simulation. If assigned as \code{gSP}, the function will access it directly.
#'
#' @import AlphaSimR
#' @return A matrix representing the initial microbial species in the current population.
#' @export
#'
#' @examples
#'
#' # Set global simulation parameters
#' gSP <- GlobalSP$new(nPop = 1000, nyear = 10, nQTLchr = 100)
#'
#' # Define the microbiota
#' gSP$setSpecies(nSpecies = 1000, nSp0 = 600, nSpEff = 100, symbiosis = c(0,1))
#'
#' # Define the trait
#' gSP$setTrait(meanP = 10, varP = 3, h2 = 0.10, m2 = 0.10)
#'
#' # Create founder genetics
#' founderG <- setFounderG(globalSP = gSP)
#'
#' # Set simulation genetic parameters
#' SP <- essentialSP(founder = founderG,
#'                   minSnpFreq = 0.05, nSnpChr = 10000)
#'
#' # Create founder microbiota
#' founderM <- setFounderM(globalSP = gSP)
#'
#' # Create the founder population
#' founderPop <- newPop(founderG)
#'
#' # Create base population
#' Pop <- randCross(founderPop,
#'                  nCrosses = gSP$nCross,
#'                  nProgeny = gSP$nSon)
#'
#' # Generate acquisition matrix for base population
#' acquiredSp <- acquiredSpecies(pop = Pop)
#'
acquiredSpecies <- function(pop, parentPop = NULL,founderM = NULL, sym = NULL,
                            rndSeed = NULL, globalSP = NULL) {

  if (is.null(globalSP)) {
    globalSP = get("gSP", envir = .GlobalEnv)
  }

  if (is.null(founderM)) {
    founderM = get("founderM", envir = .GlobalEnv)
    founderM <- founderM[["architecture"]]
  }else{
    founderM <- founderM[["architecture"]]
  }

  if(is.null(rndSeed)){
    rndSeed <- sample(c(1000:2000),1)
  }

  acquiredSp <- matrix(0, ncol = length(founderM$w), nrow = nInd(pop))

  if(is.null(parentPop)){
    set.seed(rndSeed)
    index_EM <- sample(c(1:length(founderM$w)),
                       length(founderM$w) * globalSP$EM, prob = founderM$RA_EM)
    EM_litter <- log2(founderM$EM[index_EM])*globalSP$EM

    for(ind in 1:nInd(pop)){
      acquiredSp[ind,] <- founderM$PM0 * log2(founderM$PM)* globalSP$PM
      acquiredSp[ind, index_EM] <- acquiredSp[ind, index_EM] + EM_litter

    }


  }else{

    if(is.null(sym)){
     stop("A value of symbiosis is required")
    }

    mother <- pop@mother[!duplicated(pop@mother)]
    rXo.mom <- matrix(ncol = length(founderM$w), nrow = length(mother))

    for(ind in 1:length(mother)){

      if(sym == 1){
        rXo.mom[ind, ] <- unlist(sapply(X = parentPop@misc[parentPop@id == mother[ind]],
                                        FUN = function(x)x$M_sym))
      }else{
        rXo.mom[ind, ] <- unlist(sapply(X = parentPop@misc[parentPop@id == mother[ind]],
                                        FUN = function(x)x$M))
      }

    }

    colnames(rXo.mom) <- founderM$Species
    rownames(rXo.mom) <- mother

    for(mom in mother){

      nSon_index <- which(pop@mother == mom)

      index_PM <- which(rXo.mom[rownames(rXo.mom) == mom, ] != 0)
      PM_litter <- log2(rXo.mom[rownames(rXo.mom) == mom, index_PM])*globalSP$PM

      ## Environmental microbiota
      set.seed(rndSeed)
      index_EM <- sample(c(1:length(founderM$w)),
                         length(founderM$w) * globalSP$EM, prob = founderM$RA_EM)

      EM_litter <- log2(founderM$EM[index_EM])*globalSP$EM

      for(nson in nSon_index){
        acquiredSp[nson, index_PM] <- PM_litter
        acquiredSp[nson, index_EM] <- acquiredSp[nson, index_EM] + EM_litter
      }
    }

  }

  return(round(acquiredSp))

}
